trigger:
  - develop
  - master
  - alpha

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Yarn@3
    displayName: 'Install Packages'

  - script: 'yarn run build --environment=production'
    displayName: 'Build PROD'
    env:
      target: 'prod'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - script: 'yarn run build --environment=development'
    displayName: 'Build DEV'
    env:
      target: 'dev'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/alpha'))

  - task: ArchiveFiles@2
    displayName: 'Zip dist folder'
    inputs:
      rootFolderOrFile: 'dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    condition: succeeded()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: 'dist_zip'
      publishLocation: 'pipeline'

  # - task: PublishPipelineArtifact@0
  #   displayName: 'Publish dist folder as drop artifact'
  #   inputs:
  #     targetPath: dist
