trigger:
  - develop
  - master
  - alpha

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Yarn@3
    displayName: 'Install Packages'

  - script: 'yarn run build --environment=production'
    displayName: 'Build PROD'
    env:
      target: 'prod'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - script: 'yarn run build-dev'
    displayName: 'Build DEV'
    env:
      target: 'dev'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/alpha'))

  - task: ArchiveFiles@2
    displayName: 'Zip dist folder'
    inputs:
      rootFolderOrFile: 'dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: 'dist.zip'
      replaceExistingArchive: true
    condition: succeeded()

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: 'zip-artifact'
      publishLocation: 'pipeline'
    condition: succeeded()
